language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r21.1-linux.tgz
  - tar -zxf android-sdk_r21.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  11 = 2.3.3 or API level 10
  - android list sdk -a
  - android update sdk --filter 1,2,7 --no-ui --force
install: mvn install -DskipTests=true
